name: Auto-Update Resume
on:
  repository_dispatch:  # Triggered by private repo webhook
  schedule:
    - cron: '0 0 * * 0'  # Weekly

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download latest resume
      run: |
        curl -H "Authorization: token ${{ secrets.PRIVATE_REPO_TOKEN }}" \
             -H "Accept: application/vnd.github.v3.raw" \
             -o resume.pdf \
             https://api.github.com/repos/joshuajyue/Resume/contents/Resume.pdf
    - name: Commit if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add resume.pdf
        git diff --staged --quiet || git commit -m "Auto-update resume $(date)"
        git push